bike.exe:
	g++  -std=c++11   main.cpp event.cpp events_def.cpp eventtype.cpp user_event_handler.cpp bike.pb.cpp thread_pool.cpp thread_cond.cpp thread_mutex.cpp -lprotobuf -pthread -o bike.exe
clear:
	rm -r bike.exe
